### ISSUE TITLE
[Tracking] New `falcoctl`

### ISSUE THREAD

**Issue by loresuso** [falcosecurity/falcoctl#132]
### Motivation

This issue is the main reference to list down all the tasks needed to revamp `falcoctl` and make it useful to distribute artifacts belonging to the Falco ecosystem, such as rules and plugins. We can also discuss here what features to add/remove and anything we think is relevant. We want to keep this issue as clean as possible, so if some task requires further explanation, we are going to open a new issue and insert its link here. We also add the links here once PRs are opened.

### Tasks
- [x] Implementation of the first skeleton of the commands https://github.com/falcosecurity/falcoctl/pull/131
- [x] Implementation of an image index to choose plugins for specific platforms and architectures. More information about image index: https://github.com/opencontainers/image-spec/blob/main/image-index.md#example-image-index  https://github.com/falcosecurity/falcoctl/pull/139
- [ ] Improve registry login command https://github.com/falcosecurity/falcoctl/issues/134. In general, anything that could make the command more scriptable can be useful.
- [ ] Improve UX by introducing new options, like Plain HTTP requests, skip certificate verification, provide a custom CA certificate https://github.com/falcosecurity/falcoctl/issues/135
- [x] Implementations of tests for the library used to push and pull artifacts. We could write integration tests by directly launching [distribution/distribution registry](https://github.com/distribution/distribution) from Golang test code.
- [x] Implementation of *search* functionality and index management  https://github.com/falcosecurity/falcoctl/pull/145 
- [ ] #174
- [x]  Do we want some visual elements like spinners while downloading or pushing artifacts? https://github.com/falcosecurity/falcoctl/pull/146 https://github.com/falcosecurity/falcoctl/pull/147
- [ ] Update documentation. Use images to describe how artifacts are pushed and pulled from the registry.
- [ ] Release + blog post
- [ ] ...

**Comment by loresuso** [comment]
This issue was trying to address the evolution of the new falcoctl, but it got out of track now.
