### ISSUE TITLE
[WIP] Proposal for Falcoctl installer

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/falcoctl#86]
# Falcoctl

> The main way of interfacing with Falco on Linux and Kubernetes

# Installation Experiences

## Linux
- Download static binary `falcoctl`
- `falcoctl install falco --target=local`
    - Install the driver
    - Install falco 

## Kubernetes
- Download static binary `falcoctl`
- `falcoctl install falco --target=kubernetes`
    - Install the driver
    - Deploy resources according to Kubernetes version

## Kubernetes (operator)
 - Download static binary `falcoctl`
 - `falcoctl install falco --target=kubernetes-operator`
     - Detect the version of Kubernetes 
     - Install operator based on version

#### What is "Falco" with Kubernetes

Can we define the resources that make up "Falco"?

# Falcoctl Requirements

## Versioning

Users should be able to choose the version of:
- falco
- driver 

Furthermore, `falcoctl` should be able to interact with different versions of Kubernetes (eg. setting the correct API version on resources, see #72). 

For example, we could implement something like:
```
.
├── cmd
├── defaults
│   ├── falco.1.15.go
│   ├── falco.1.16.go
│   └── falco.1.17.go
└── main.go
```

#### Minimim supported versions:
- Falco: _TBD / maybe 0.22_
- Kubernetes: _TBD_

## Upstreams

| Name | Versioned | Upstream | Note |
| -------- | -------- | -------- | -------- |
| [falco-driver-loader](https://github.com/falcosecurity/falco/issues/1125) | Y | https://dl.bintray.com/falcosecurity/bin/ | See [here](https://github.com/falcosecurity/falco/issues/1125) |
| drivers    | Y | https://dl.bintray.com/falcosecurity/driver/ |
| falco packages (deb, rpm, bin)    | Y | https://dl.bintray.com/falcosecurity/bin/ |  |
| falco images     | Y | https://hub.docker.com/r/falcosecurity/falco | |
| rules     | ? | ? |  |

## Internal features

- [ ] download and wrap `falco-driver-loader`  👉 [falcoctl#88](https://github.com/falcosecurity/falcoctl/issues/88)  
- [ ] build driver with `falco-driver-loader` and driverkit 👉 [falcoctl#88](https://github.com/falcosecurity/falcoctl/issues/88), [falcoctl#81](https://github.com/falcosecurity/falcoctl/issues/81)
- [ ] preflight check
- [ ] "smart install" for Kubernetes 👉 [falcoctl#73](https://github.com/falcosecurity/falcoctl/issues/73)
- [x] cert materials generation 
- [ ] fetch rules? 

## Automation Tasks

| Action | Subject | Prep. Task | Linux | Kubernetes |
| -------- | -------- | -------- | -------- | -------- |
| **Install** | driver | download `falco-driver-loader` | run `falco-driver-loader`, fallback to driverkit     | N/A     |
| **Remove** | driver |  | run `falco-driver-loader unload` ?   | N/A   |
| **Update** | driver |  | **Remove**, then **Install**   | N/A |
| **Install** | falco   | preflight check  | download and install package | create daemonset |
| **Remove** | falco   |  | uninstall package | delete daemonset |
| **Update** | falco   |  | update package | update daemonset |
| **Install** | TLS      | cert materials generation | copy files to path      | create secret |
| **Remove** | TLS      |  | delete files from path      | delete secret |
| **Update** | TLS      |  | **Remove**, then **Install**      | delete secret |
| **Install** | Rules      | fetch rules? | copy files to path, update config | update configmap  |
| **Remove** | Rules     |  | delete files from path, update config      | update configmap |
| **Update** | Config     |  | modify `falco.yml`      | update configmap |

Note:
 - Installing the driver on Kubernetes should not be supported directly by `falcoctl`. This process requires an installation on the host or by a privileged init-container

Questions:
 - When does Falco need to be reloaded?
 - Config hot-reloading? #69

WIP updated by @leogr

**Comment by kris-nova** [comment]
I wrote a lot more of this up https://github.com/falcosecurity/falco/issues/1114#issuecomment-604580503

Basically I think falcoctl should have a `kubeadm` like experience and the more I think about it - the more I think the paradigm that you can "use kubernetes to install falco" is broken.

**Comment by leogr** [comment]
Question:
Should Kubernetes be the default [target](https://github.com/falcosecurity/falcoctl/issues/65#issuecomment-604897108) ?

**Comment by leogr** [comment]
Update: after a long talk with @fntlnz and @leodido we all agree that makes sense to leave the driver downloading and installation logic inside the falco-driver-loader. Furthermore, with very few improvements, [it can be used by falcoctl](https://github.com/falcosecurity/falco/issues/1125) in a versioned way.

**Comment by leogr** [comment]
Hey @kris-nova I've update the issue description

**Comment by leogr** [comment]
Replaced by #95 - feel free to reopen this (or a new one) if something important is missing.
